@tagId = 4
@projectId =1
@taskId =1

### create tag
POST http://localhost:8080/tags
Content-Type: application/json

{
  "tagName" : "완성",
  "projectId" : 1
}

### update tag
PUT http://localhost:8080/tags/{{tagId}}
Content-Type: application/json

{
  "tagName" : "complete",
  "projectId" : 1
}

### delete tag
DELETE http://localhost:8080/tags/{{tagId}}




### get tags (projectId)
GET http://localhost:8080/projects/{{projectId}}/tags

### get tags (taskId)
GET http://localhost:8080/tasks/{{taskId}}/tags

### post task에 tag 등록
POST http://localhost:8080/tasks/tag
Content-Type: application/json

{
  "taskId": 1,
  "tagId": 5
}

### delete task에 tag 삭제
DELETE http://localhost:8080/tasks/tag
Content-Type: application/json

{
  "taskId": 1,
  "tagId": 4
}

